"""tablas del nucleo

Revision ID: 0001
Revises: 
Create Date: 2026-10-07 10:39:39.253507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('name_normalized', sa.String(length=150), nullable=False),
    sa.Column('muscle_group', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_normalized')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('height_cm', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(length=20), nullable=True),
    sa.Column('level', sa.Enum('principiante', 'intermedio', 'avanzado', name='ck_level', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('goal', sa.Enum('masa', 'fuerza', 'perder_grasa', 'condicion_general', 'mantenerme_activo', name='ck_goal', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('days_per_week', sa.Integer(), nullable=False),
    sa.Column('session_minutes', sa.Integer(), nullable=False),
    sa.Column('equipment', sa.Enum('gimnasio', 'mancuernas', 'casa', name='ck_equipment', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.Column('legal_notice_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('days_per_week BETWEEN 1 AND 7', name='ck_profiles_days'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('week_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'closed', name='ck_planstatus', native_enum=False, create_constraint=True, length=32), server_default='draft', nullable=False),
    sa.Column('origin', sa.Enum('generated', 'improved', name='ck_planorigin', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('original_routine', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_week_plans_user_week', 'week_plans', ['user_id', 'week_start'], unique=False)
    op.create_table('plan_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_plan_id', sa.Integer(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.CheckConstraint('day_index BETWEEN 1 AND 7', name='ck_plan_days_index'),
    sa.ForeignKeyConstraint(['week_plan_id'], ['week_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_plan_id', 'day_index', name='uq_plan_days_week_day')
    )
    op.create_table('plan_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_day_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('target_weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('edited_by_user', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['plan_day_id'], ['plan_days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_day_id', 'position', name='uq_plan_exercises_day_pos')
    )
    op.create_table('workout_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_day_id', sa.Integer(), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('feeling', sa.Enum('easy', 'good', 'hard', 'pain', name='ck_feeling', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_day_id'], ['plan_days.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('set_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('plan_exercise_id', sa.Integer(), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('effort', sa.Integer(), nullable=True),
    sa.CheckConstraint('effort BETWEEN 1 AND 10', name='ck_set_entries_effort'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['plan_exercise_id'], ['plan_exercises.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('set_entries')
    op.drop_table('workout_sessions')
    op.drop_table('plan_exercises')
    op.drop_table('plan_days')
    op.drop_index('ix_week_plans_user_week', table_name='week_plans')
    op.drop_table('week_plans')
    op.drop_table('profiles')
    op.drop_table('users')
    op.drop_table('exercises')
    # ### end Alembic commands ###
