"""fin de sesion y cierre de semana

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-07 12:09:05.563967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('week_plans', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workout_sessions', sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_sessions', 'finished_at')
    op.drop_column('week_plans', 'closed_at')
    # ### end Alembic commands ###
