"""series planificadas e indicaciones

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-07 16:13:30.795040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('target_weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['plan_exercise_id'], ['plan_exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_exercise_id', 'set_number', name='uq_plan_sets_exercise_num')
    )
    op.add_column('plan_exercises', sa.Column('execution_notes', sa.Text(), nullable=True))
    op.drop_column('plan_exercises', 'reps')
    op.drop_column('plan_exercises', 'sets')
    op.drop_column('plan_exercises', 'target_weight_kg')
    op.add_column('set_entries', sa.Column('plan_set_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_set_entries_plan_set_id', 'set_entries', 'plan_sets', ['plan_set_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_set_entries_plan_set_id', 'set_entries', type_='foreignkey')
    op.drop_column('set_entries', 'plan_set_id')
    op.add_column('plan_exercises', sa.Column('target_weight_kg', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True))
    # Las columnas obligatorias se recrean con un valor temporal para no fallar si ya hay filas.
    # Al volver atrás se pierde el detalle por serie (plan_sets se borra): los valores quedan en 0.
    op.add_column('plan_exercises', sa.Column('sets', sa.INTEGER(), autoincrement=False, nullable=False, server_default='0'))
    op.add_column('plan_exercises', sa.Column('reps', sa.INTEGER(), autoincrement=False, nullable=False, server_default='0'))
    op.alter_column('plan_exercises', 'sets', server_default=None)
    op.alter_column('plan_exercises', 'reps', server_default=None)
    op.drop_column('plan_exercises', 'execution_notes')
    op.drop_table('plan_sets')
    # ### end Alembic commands ###
