"""cardio con duracion

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-08 13:15:43.812096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('kind', sa.Enum('strength', 'cardio', name='ck_exercisekind', native_enum=False, create_constraint=True, length=32), server_default='strength', nullable=False))
    op.add_column('plan_sets', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.alter_column('plan_sets', 'reps',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('set_entries', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.alter_column('set_entries', 'reps',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('set_entries', 'weight_kg',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               nullable=True)
    # ### end Alembic commands ###

    # Alembic no genera las restricciones CHECK de "repeticiones o minutos": se agregan a mano.
    # (La del tipo de ejercicio, ck_exercisekind, la crea el propio Enum.)
    # Una serie se mide en repeticiones (fuerza) o en minutos (cardio): una cosa o la otra.
    op.create_check_constraint(
        'ck_plan_sets_reps_or_duration', 'plan_sets',
        '(reps IS NOT NULL) <> (duration_minutes IS NOT NULL)',
    )
    op.create_check_constraint(
        'ck_set_entries_reps_or_duration', 'set_entries',
        '(reps IS NOT NULL) <> (duration_minutes IS NOT NULL)',
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('ck_exercisekind', 'exercises', type_='check')
    op.drop_constraint('ck_set_entries_reps_or_duration', 'set_entries', type_='check')
    op.drop_constraint('ck_plan_sets_reps_or_duration', 'plan_sets', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('set_entries', 'weight_kg',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               nullable=False)
    op.alter_column('set_entries', 'reps',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('set_entries', 'duration_minutes')
    op.alter_column('plan_sets', 'reps',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('plan_sets', 'duration_minutes')
    op.drop_column('exercises', 'kind')
    # ### end Alembic commands ###
